a=int(input("enter integer value\n"))
b=input("enter string value\n")
c=float(input("enter float value\n"))
d=bool(input("enter boolean\n"))
e=input("enter a char\n")
print(a,b,c,d,e)
mylist=[a,b,c,d,e]
print(mylist)
# mylist.remove(e)
print(mylist)
print(mylist[::-1])
# print(mylist)
print(mylist.pop(2))
print(mylist)